version: "2"

services:
  cam:
    container_name: camtools
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    environment:
      ASPNETCORE_ENVIRONMENT: 'Production'      
      ASPNETCORE_URLS: http://+:7070
    expose:
      - "7070"
    ports:
      - "7070:7070"
 
# Remember to start the network before running this file:
# $ docker network create crossword-net
#
# Then you can start each of the docker-compose.yml files like this:
# $ docker-compose -f project_one/docker-compose.yml up -d
# $ docker-compose -f project_two/docker-compose.yml up -d
networks:
  default:
    external:
      name: crossword-net
